### ISSUE TITLE
Library not found for -lPods-GuidanceApp

### ISSUE THREAD

**Issue by kochizufan** [heremaps/here-ios-sdk-examples#101]
Hi 

I try to compile turn-by-turn-navigation-ios-swift.
I put appID, appCode and licenseKey into AppDelegate.swift, modify Bundle Identifier, and run "pod install" on turn-by-turn-navigation-ios-swift folder.

Then I run build function, 1 error occurred: "Library not found for -lPods-GuidanceApp"

![スクリーンショット 2019-05-13 16 12 56](https://user-images.githubusercontent.com/2221431/57602457-16d54600-759a-11e9-8aae-cd5c753437da.png)

What can I do for this?
What procedure I missed?

Regards,

**Comment by f4st** [comment]
Hello @kochizufan,

Thank you for asking the question.
From the described linkage error it seems that you opened **GuidanceApp.xcodeproj** instead of **GuidanceApp.xcworkspace**.
Please ensure that you have opened the CocoaPods generated workspace file (**GuidanceApp.xcworkspace**). When you open the **GuidanceApp.xcworkspace** you should see 2 projects inside:
![Project_structure](https://user-images.githubusercontent.com/3294690/57611514-bafbc480-757b-11e9-8950-b6bc6114526b.png)

After that Build and Run the GuidanceApp.

Kind regards,
@f4st

**Comment by kochizufan** [comment]
Hi @f4st,

Yes you are right, with xcworkspace, it works.

Thank you very much!
