### ISSUE TITLE
Public transport routing walkSpeed doesn't work

### ISSUE THREAD

**Issue by moment101** [heremaps/here-ios-sdk-examples#132]
Hi, 
I used SDK to get public transport route, but the result are different from HERE WeGo (HERE iOS App). And I found the walk time are various. I try modify the walkSpeed of NMARoutingMode, but the walk time of route didn't change. (walkSpeed doesn't work)

If anyone know how to adjust the walk speed over iOS SDK ? Thanks.

sdk version 3.13.2

**Comment by SiriUS2551AK** [comment]
Hi @moment101 ,
It looks like you are trying to use **the Urban Mobility** feature. Is it true?

The **walkSpeed** property is defined as part of the urban mobility in a category **NMARoutingMode+UrbanMobility.h**.
So, according to [the official documentation ](https://www.developer.here.com/documentation/ios-premium/api_reference_jazzy/Urban%2520Mobility.html)

> DEPRECATED: As of SDK 3.8.

Due to the fact that the feature is deprecated, the behavior will not be fixed.

**Comment by moment101** [comment]
Thanks @SiriUS2551AK ,
Got it.
