### ISSUE TITLE
Non-public API Usage in NMAKit

### ISSUE THREAD

**Issue by OliverQuantumDevs** [heremaps/here-ios-sdk-examples#143]
Hey,

Our App is utilising the speedLimit aspect of the HERE SDK, We've pushed an initial build to apple but they're coming back with a Non-public API usage issue.

I'd read on a few threads and forums that a fix will be brought out, But I cant see and update on this?

> ITMS-90338: Non-public API usage - The app references non-public symbols in Frameworks/NMAKit.framework/NMAKit: _getcontext, _makecontext, _setcontext. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/

The specific Pod im using is `pod 'HEREMapsUI'`

Thanks
Oliver

**Comment by dashchak** [comment]
Hi @OliverKDMIreland 
Looks like you use the latest MSDKUI v2.1.3, which depends on HERE Maps v3.13. 
See [release page](https://github.com/heremaps/msdkui-ios/releases).
The root cause of [issue you faced](https://stackoverflow.com/questions/58214571/ios-here-sdk-nmakit-private-api-usage) is in HERE Maps v3.13 which introduced it. 

There are 2 options for you now:
1. Wait for next HEREMapsUI release which will switch to HERE Maps v3.13.3 or even v3.14 
2. Switch back to HEREMapsUI v2.1.2 which uses HEREMaps v3.12

**Comment by OliverKDMIreland** [comment]
Thanks for the speedy reply @dashchak 

I'll go ahead and try your second suggestion now. But do you have any estimate on when the new release will be? We're hoping to fully release our Apps in mid January

Thanks
Oliver

**Comment by datasun** [comment]
@OliverKDMIreland The team is working on an update for [MSDKUI](https://github.com/heremaps/msdkui-ios) to integrate the next HERE SDK Premium version. There's no clear estimation yet, but most likely it will not arrive before your due date. Once we have it available, it will be announced [here](https://github.com/heremaps/msdkui-ios/releases). Hope this helps at least a little bit. Thanks for your understanding.
